"""Alter database

Revision ID: 2bd67e9b019e
Revises: 
Create Date: 2023-07-29 12:03:27.349161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd67e9b019e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaces',
    sa.Column('space_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name_space', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('space_id')
    )
    op.create_table('lists_in_clickup',
    sa.Column('list_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('list_name', sa.String(length=255), nullable=False),
    sa.Column('clickup_space', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['clickup_space'], ['spaces.space_id'], ),
    sa.PrimaryKeyConstraint('list_id')
    )
    op.create_table('courses_in_classroom',
    sa.Column('course_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('clickup_list_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['clickup_list_id'], ['lists_in_clickup.list_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('works_in_clickup',
    sa.Column('work_id', sa.BigInteger(), nullable=False),
    sa.Column('task_clickup_id', sa.String(length=255), nullable=False),
    sa.Column('work_title', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link_to_work', sa.Text(), nullable=True),
    sa.Column('classrom_course_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['classrom_course_id'], ['courses_in_classroom.course_id'], ),
    sa.PrimaryKeyConstraint('work_id'),
    sa.UniqueConstraint('task_clickup_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works_in_clickup')
    op.drop_table('courses_in_classroom')
    op.drop_table('lists_in_clickup')
    op.drop_table('spaces')
    # ### end Alembic commands ###
