"""Alter type task clickup id in WorksInClickUp

Revision ID: 5de48337e056
Revises: 647b4fbeecb7
Create Date: 2023-07-22 14:30:43.291148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5de48337e056'
down_revision = '647b4fbeecb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_in_clickup', 'task_clickup_id',
               existing_type=mysql.BIGINT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works_in_clickup', 'task_clickup_id',
               existing_type=sa.String(length=255),
               type_=mysql.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
