"""Creation of base tables

Revision ID: f14617331956
Revises: a15e2b9039c1
Create Date: 2023-04-09 19:11:11.319817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14617331956'
down_revision = 'a15e2b9039c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses_in_classroom',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('clickup_list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clickup_list_id'], ['lists_in_clickup.list_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('lists_in_clickup',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('list_id'),
    sa.UniqueConstraint('space_id')
    )
    op.create_table('works_in_clickup',
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('task_clickup_id', sa.Integer(), nullable=False),
    sa.Column('work_title', sa.String(length=255), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link_to_work', sa.Text(), nullable=True),
    sa.Column('classrom_course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classrom_course_id'], ['courses_in_classroom.course_name'], ),
    sa.PrimaryKeyConstraint('work_id'),
    sa.UniqueConstraint('task_clickup_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works_in_clickup')
    op.drop_table('lists_in_clickup')
    op.drop_table('courses_in_classroom')
    # ### end Alembic commands ###
